### ISSUE TITLE
Add info/update about xterm.js, Hyper.app, VSCode

### ISSUE THREAD

**Issue by XVilka** [termstandard/colors#17]
Since they support true colors now

**Comment by pocc** [comment]
For Hyper.app on Macos, true colors are still not supported. This is for the latest release of Hyper.app, 3.0.2.

<img width="561" alt="Screen Shot 2019-07-03 at 1 27 05 PM" src="https://user-images.githubusercontent.com/10995145/60622921-492f4280-9d96-11e9-960a-7e26cdf7cebb.png">

**Comment by Tyriar** [comment]
Hyper supported true color in its late v2 versions, [in v3](https://hyper.is/blog) they moved to the WebGL renderer which lacked true color until recently. When they update and release based on [xterm.js 4.3.0](https://github.com/xtermjs/xterm.js/releases/tag/4.3.0) it will be supported again.
