### ISSUE TITLE
Stronger collaboration

### ISSUE THREAD

**Issue by BridgeAR** [termstandard/colors#35]
@XVilka are you open for others to join the termstandard organization to drive this further in collaboration? :-)

**Comment by XVilka** [comment]
Are there any volunteers?

**Comment by BridgeAR** [comment]
I would like to join. What about others that contributed before like @pocc?

**Comment by kurahaupo** [comment]
@XVilka  count me in too

**Comment by XVilka** [comment]
As @BridgeAR and @kurahaupo are now part of the organization, I am closing this as resolved. Thank you, everyone!

**Comment by XVilka** [comment]
@kurahaupo sorry, for some reason the "base role" for organization members was just "Read", not sure why. I changed it to "Write", should work now. Let me know if something doesn't work still.

**Comment by kurahaupo** [comment]
Looks like it's working now.
