### ISSUE TITLE
People are still adding comments to the old gist

### ISSUE THREAD

**Issue by kurahaupo** [termstandard/colors#43]
The comments thread on the old gist is so long that it's very easy for people to miss the "obvious" notice at the top, especially after they've spend 10 minutes reading down the rest of it.

Please modify the gist to:
* hide all its comments; and
* remove all its current content (don't worry, it has a git log like everything else, so it's not really gone); and
* add an explanation and link pointing to this repo.

**Comment by XVilka** [comment]
Thank you, it's done.
