### ISSUE TITLE
How to get 256 color support for FreeBSD 13 headless machine?

### ISSUE THREAD

**Issue by rajhlinux** [termstandard/colors#46]
Hello I have FreeBSD 13 headless with a graphics card of "AMD Radeon PRO WX 2100".

Can this color library provide 256 color support on the headless machine?

I basically want to avoid the installing a full package of desktop environment just to have color support for one application which is terminal/console.

Thanks.

**Comment by XVilka** [comment]
@rajhlinux it's not a library but an index. By "headless," I assume you meant the SSH? Nothing is needed at all, as long as your client terminal supports it.
