### ISSUE TITLE
Use SemVer

### ISSUE THREAD

**Issue by pocc** [termstandard/colors#6]
[SemVer](https://semver.org/) is the industry standard means of software versioning. Github allows projects to adhere to this with tagging.

This document (as gist) has over 140 commits, so it's seen significant changes. I am proposing this usage of SemVer for this project:

- __MAJOR__ : Change in the scope of this document ( #7 )
- __MINOR__ : Change in status of one of the tracked programs. Change in background/detection infos
- __PATCH__ : Spelling/Grammar

I would like to hear what people's thoughts are on this.

**Comment by pocc** [comment]
Patch may be pointless for a document like this as tracking minor changes is more effort than its worth.

**Comment by felixrabe** [comment]
I think as long as the document is primarily viewed within a Git-supporting context (such as the Gist or this repo on GitHub), the most important information regarding versioning – its timestamp – is always clearly communicated. IMHO no separate version number is necessary as long as I know if what I'm reading is up to date.

**Comment by felixrabe** [comment]
Anyhow, more important than slapping a semver on the doc itself is clearly stating within the doc the exact version / point in time / commit (preferably all of it together :) ) of the referred project (terminal or application) the information applies to. Different parts of the document may be more current than others, and it's always good to know what is what.

**Comment by felixrabe** [comment]
(Btw: Awesome work on curating this information in the first place @XVilka! I'm just passing by and found it very insightful.)

**Comment by pocc** [comment]
Yeah now that I think about it, semver is used so that dependencies can be tracked. This project will not be conceivably used as a dependency. 

Agree that timestamp (or commit) will be most relevant here, if ever.

@felixrabe cheers for the input - closing as you have a good point
