### ISSUE TITLE
Change repo name to truecolor

### ISSUE THREAD

**Issue by pocc** [termstandard/colors#8]
I think "colors" is ambiguous. I think it should be changed to "truecolor" for these reasons:

- It's more descriptive
- It's the name of the gist that this repo comes from
- It's one of the values of $COLORTERM (other being 24bit) indicating truecolor support
- It's the term (with a space) that is used to search on google for this concept

This repo was only recently created, so changing the name shouldn't be too impactful (and github will still provide redirects). Thoughts?

**Comment by pagerc** [comment]
@VortexCortex previously [mentioned](https://gist.github.com/XVilka/8346728#gistcomment-2154981)

> p.s. I would like to add that "TRUECOLOR" is a registered trademark of Microsoft and therefore is a string that should / would be avoided by any knowledgeable FLOSS developer on this planet.

Comment still stands true now as then.

**Comment by pocc** [comment]
That's a good point. There are still other options that are more descriptive. Thinking out loud:

- `24bitcolor`
- `RGBcolor`
- `colordepth` (the user is termstandard, and so helps describe the repo name)
- `SGRparams` per the [wikipedia section](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters)

**Comment by pagerc** [comment]
I humbly submit 24bitRGBcolordepthSGRparams

**Comment by pocc** [comment]
At the end of the day, this is @XVilka's decision, so changing name or closing this issue is up to him.

**Comment by pocc** [comment]
Closing this as time has passed and it's not getting any interest.

**Comment by craigbarnes** [comment]
> There are still other options that are more descriptive. Thinking out loud:
> 
> * `24bitcolor`
> * `RGBcolor`
> ...

What about "bikeshed"? I propose we paint it green.

**Comment by XVilka** [comment]
It is not a bikeshed anymore - as you can see most of the terminals already adopted it.
